language: php
php:
    - '7.0'
    - '7.1'
install:
    - composer install --dev --no-interaction
script:
    - mkdir -p build/logs
    - php vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover ./build/logs/clover.xml
after_success:
    - travis_retry php vendor/bin/coveralls -v
